### ISSUE TITLE
Search Form

### ISSUE THREAD

**Issue by AnnekeSchuette** [AnnekeSchuette/capstone-project#15]
## Value statement

As a **user** 
I **need a bookmarking function on wine cards**
so that I can  ** add** them to a list of saved wines to quickly find them later on

## Description 
<img width="313" alt="image" src="https://user-images.githubusercontent.com/77288350/111144121-ef30d980-8586-11eb-905d-89e1f66a6882.png">

## Acceptance criteria
- [ ] every WineCard has a Bookmark Icon 
- [ ] the bookmark-icon has two visual states: active / inactive (default)
- [ ] the state toggles on click
- [ ] bookmarked wines are **saved** into an array _savedWines_
- [ ] de-bookmarked Wines are **removed** from the array _savedWines_

## Tasks
- [ ] Extend unit tests for WineCard with bookmarking
- [ ] Add bookmark-Icon to WineCard component
- [ ] Style the two states

Integrate bookmark function in App, which
- [ ]  toggles state on click and 
- [ ] saves wines to a new array or removes them, when de-bookmarked
- [ ] Test on mobile and desktop
