### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by AnnekeSchuette** [AnnekeSchuette/capstone-project#16]
## Value statement

As a **user** 
I **need** a navigation
so that I can  **access** all pages of the app

## Description 
**Navigation component**
<img width="654" alt="image" src="https://user-images.githubusercontent.com/77288350/111144955-08865580-8588-11eb-95f9-b2bdc5e0d8aa.png">

## Acceptance criteria
- [ ] the _Navigation_ shows two nav items: "Explore" and "Wine Storage" (see wireframes above)
- [ ] the corresponding nav item for the active page is highlighted (see wireframes above)
- [ ] the app initially renders "ExplorePage" 
- [ ] the correct page is rendered on click
- [ ] the subtitle in app header is changes to "Wine Storage" on page switch

## Tasks
**ExplorePage**
- [ ] create own page component _ExplorePage_ for existing list of wine recommendations (current home) 

**Navigation component**
- [ ] Write unit tests for Navigation component
- [ ] Create a Navigation Component
- [ ] Create/expand router for "ExplorePage" and "WineStoragePage"
- [ ] test in browser + mobile
