### ISSUE TITLE
Category Cards

### ISSUE THREAD

**Issue by AnnekeSchuette** [AnnekeSchuette/capstone-project#2]
## Value statement

As a **user** 
I **need to see food categories**
so that I can  **choose the food** I want to **find a wine for** 

## Description (Text, Scribble, Wireframe, Design)
<img width="559" alt="image" src="https://user-images.githubusercontent.com/77288350/110210780-916c0580-7e93-11eb-9df6-a54ff6fbef64.png">

## Acceptance criteria
- [ ] List Categories and Subcategories are liste
- [ ] They are placed on a card which expands over full with

## Tasks
- [ ] Write Test
- [ ] Create form component (Storybook)
- [ ] Add styling
- [ ] Test on mobile and desktop
