### ISSUE TITLE
WineDetail Component

### ISSUE THREAD

**Issue by AnnekeSchuette** [AnnekeSchuette/capstone-project#20]
## Value statement

As a **user**
I **need to see** details about a wine when I click on a WineCard
so that I can **read more information about it**

## Description (Text, Scribble, Wireframe, Design)
<img width="284" alt="image" src="https://user-images.githubusercontent.com/77288350/112142767-4b26de00-8bd7-11eb-8d41-27450550680a.png">

## Acceptance criteria

The detail page/overlay
- [x] shows the title, full description, price, average rating, score
- [x] displays an image
- [x] renders a deeplink as button or textlink (external)

## Tasks
- [x] Add Router
- [x] Write Tests
- [x] Add styling
- [x] Test on mobile and desktop
